version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  app:
    build:
      context: . # Use the current directory as the build context (where your Dockerfile is located)
    ports:
      - "13001:4200"
    volumes:
      - .:/app
    command: npm run dev

volumes:
  postgres-data:
  app-code:
